services:
  # rtsp:
  #     build: .
  #     container_name: my_rtsp_server
  #     devices:
  #       - /dev/video0:/dev/video0
  #     command: /opt/v4l2rtspserver/build/v4l2rtspserver -W1920 -H1080 -F30 /dev/video0
  #     ports:
  #       - 8554:8554
  #     restart: always

  yolov8ds:
    # image: dgpu-yolov8ds
    container_name: yolov8ds
    runtime: nvidia
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /home/rakesh/Work/yolov8DS/yolov8-deepstream-6-1:/app
      - /dev/video0:/dev/video0
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    stdin_open: true
    tty: true
    restart: no  # This prevents the container from restarting and can be removed with `docker-compose down`
    command: /app/start.sh